server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: milvus
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
  relabel_configs:
    - source_labels: [__meta_docker_name]
      regex: milvus-standalone
      action: keep
    - source_labels: [__meta_docker_name]
      target_label: job
      replacement: milvus
    - source_labels: [__meta_docker_name]
      target_label: container
      replacement: milvus-standalone
  pipeline_stages:
    - docker: {}

